# Generated by Django 5.2.7 on 2025-11-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cartitem'),
        ('sales', '0002_sale_payment_method_alter_sale_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Shipped'), ('CUSTOMER_CHANGE', 'Customer Changed Mind'), ('OTHER', 'Other')], default='CUSTOMER_CHANGE', max_length=50)),
                ('sale', models.ForeignKey(help_text='The original sale transaction being returned.', on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of this product being returned.')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at time of original sale.', max_digits=10)),
                ('subtotal_refund', models.DecimalField(decimal_places=2, help_text='Calculated amount to refund for this item.', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('return_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.return')),
            ],
        ),
    ]
